version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5555:80"
    # volumes:
    #   - .:/app
    restart: always
    env_file:
      - .env


networks:
  langchain-simple-rest:
    driver: bridge